# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do
  lane :beta do |values|
    # Before calling match, we make sure all our devices are registered on the Apple Developer Portal
    register_devices(
      devices_file: "./fastlane/devices.txt",
      username: 'iura.gaitur@gmail.com'
    )

    # After registering the new devices, we'll make sure to update the provisioning profile if necessary
    # options for type are "adhoc", "development", "appstore"
    match(
      force_for_new_devices: true,
      type: "development",
      # readonly: true  #readonly mode to be sure it won't create any new certificates or profiles.
    )

    # Change build number (requirement of Testflight).
    increment_build_number(
      xcodeproj: "./System_Pro.xcodeproj"
    )
    # Build a release
    gym(
      scheme: "System_Pro",
      clean: true,
      #workspace: "./AppName.xcworkspace" # since using pods
      project: "./System_Pro.xcodeproj"
    )


    # Upload release to crashlytics
    crashlytics(api_token: '3627a4cd64d7d15f35ae9efb8fa3bc5471bb12a6',
                    build_secret: 'e63992d20c2b19e16ab26f2834a8115af48b7b3797973bf57966dcf750ac5c71',
                    notes: changelog,
                    groups: 'Default')
    # You can notify your team in chat that a beta build has been uploaded
    # slack(
    #   slack_url: "https://hooks.slack.com/services/YOUR/TEAM/INFO"
    #   channel: "beta-releases",
    #   message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    # )
  end
end