# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
# Deploy to google play
  #desc "Deploy a new version to the Google Play"
  #lane :deploy do
  #  gradle(task: "clean assembleRelease")
  #  upload_to_play_store
  #end

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: 'assemble', build_type: 'Release')
    changelog = prompt( text: "Changelog: ", multi_line_end_keyword: "END")
    crashlytics(api_token: '3627a4cd64d7d15f35ae9efb8fa3bc5471bb12a6',
                build_secret: 'd011fc19807b41e2014c75d875db7a1f8f9018aed4403b32145bf423ea087785',
                notes: changelog,
                groups: 'Default'
                )
    slack(
        message: "App successfully released!",
        slack_url: "https://hooks.slack.com/services/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",  # Optional, by default will post to the default channel configured for the POST URL.
        success: true,        # Optional, defaults to true.
        payload: {  # Optional, lets you specify any number of your own Slack attachments.
          "Build Date" => Time.new.to_s,
          "Built by" => "Jenkins",
        }
      )
  end
end
